/*
 * This file is generated by jOOQ.
 */
package springboot.webapp.usersmanager.generated_sources.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import springboot.webapp.usersmanager.generated_sources.jooq.tables.Polygon;
import springboot.webapp.usersmanager.generated_sources.jooq.tables.Users;
import springboot.webapp.usersmanager.generated_sources.jooq.tables.records.PolygonRecord;
import springboot.webapp.usersmanager.generated_sources.jooq.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PolygonRecord> POLYGON_PKEY = Internal.createUniqueKey(Polygon.POLYGON, DSL.name("polygon_pkey"), new TableField[] { Polygon.POLYGON.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
