/*
 * This file is generated by jOOQ.
 */
package springboot.webapp.usersmanager.generated_sources.jooq;


import springboot.webapp.usersmanager.generated_sources.jooq.tables.Polygon;
import springboot.webapp.usersmanager.generated_sources.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.polygon</code>.
     */
    public static final Polygon POLYGON = Polygon.POLYGON;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
